### ISSUE TITLE
Сode runs with warning

### ISSUE THREAD

**Issue by anastasia-stepanchenko** [QuantLet/QID-2455-MVAbankrupt#3]

**Comment by polarstern** [comment]
> fit   = glm(y ~ x3 + x4 + x5, family = binomial(link = "logit"))
Warning message:
glm.fit: fitted probabilities numerically 0 or 1 occurred

**Comment by polarstern** [comment]
So?

**Comment by lborke** [comment]
Create a new datafield in the metainfo.txt and put the warning text into this field:

see:
https://github.com/QuantLet/QID-1716-MVAdrug3waysTab/issues/2#issuecomment-154393958
